dist: trusty
sudo: false

language: go

env:
    matrix:
        - TEST_FOR_SERVER=true
        - TEST_FOR_CLIENT=true

before_script:
    # Setup Nodejs to run client-side toolchain.
    # Parhaps we should create and run Docker container which includes binary to test this repository.
    - nvm install 6
    - curl -o- -L https://yarnpkg.com/install.sh | bash # install yarn pkg
    - export PATH=$HOME/.yarn/bin:$PATH # add `yarn` to path.

script:
    - ./script/travis_test.sh

matrix:
    allow_failures:
        # ESLint fails currently
        - env: TEST_FOR_CLIENT=true

notifications:
    email: false

